# This is a basic workflow to help you get started with Actions

name: test

# 触发 workflow 的事件
on:
  push:
    # 分支随意2
    branches:
      - main
      
# 一个workflow由执行的一项或多项job
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: execute py script
        env:
          FM_USERNAME: ${{ secrets.USERNAME }}
        run: |
          python genertor-json.py
      - name: 列出所有文件
        run: |
          ls -l
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.3.0
        with:
          github_token: ${{secrets.PUSH_TOKEN}}

